openapi: 3.0.0
info:
  title: Project API
  version: 1.0.0
  description: API for managing projects
paths:
  /projects:
    get:
      tags:
        - Projects
      summary: Get all projects
      description: Retrieve a list of all projects
      responses:
        '200':
          description: A list of projects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SaveProjectReq'
    put:
      tags:
        - Projects
      summary: Create a new project
      requestBody:
        description: The project to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SaveProjectReq'
            example: {
              "description": "Project 1",
              "startDate": "2020-01-01T00:00:00.000Z",
              "endDate": "2020-01-01T00:00:00.000Z",
              "isPrivate": true,
              "tasks": [
                {
                  "taskName": "Task 1",
                  "taskDescription": "Task 1",
                  "status": "TODO"
                }
              ]
            }
      responses:
        '201':
          description: The created project
  /projects/{id}:
    get:
      tags:
        - Projects
      summary: Get a project by id
      description: Retrieve a project by id
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
          description: The project id
      responses:
        '200':
          description: A project
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectDto'
  /projects/filter:
    post:
      tags:
        - Projects
      summary: Filter projects
      requestBody:
        description: The project properties to filter by
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectDto'
      responses:
        '200':
          description: The filtered projects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProjectDto'
components:
  schemas:
    ProjectDto:
      $ref: './api/project/Project.json#/ProjectDto'
    ProjectFilterDto:
      $ref: './api/project/Project.json#/ProjectFilterDto'
    TaskDto:
      type: object
      properties:
        taskName:
          type: string
        taskDescription:
          type: string
        project:
          type: integer
          format: int64
        status:
          type: string
    SaveProjectReq:
      allOf:
        - $ref: '#/components/schemas/ProjectDto'
        - type: object
          properties:
            tasks:
              type: array
              items:
                $ref: '#/components/schemas/TaskDto'




