spring:
  application:
    name: @project.artifactId@
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
  datasource:
    username: ${app.username}
    password: ${app.password}
    url: ${app.url}
  liquibase:
    change-log: classpath:/db/changelog-master.xml
    enabled: true
    user: ${app.username}
    password: ${app.password}
    url: ${app.url}

logging:
  level:
    org:
      springframework:
        jdbc:
          datasource=DEBUG: DEBUG


app:
  # DB Properties
  url: jdbc:postgresql://localhost:5432/fc
  username: fc
  password: changeit