spring:
  application:
    name: @project.artifactId@
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
  datasource:
    username: ${app.username}
    password: ${app.password}
    url: ${app.url}
  liquibase:
    change-log: classpath:/db/changelog-master.xml
    enabled: true
    user: ${app.username}
    password: ${app.password}
    url: ${app.url}
    
server:
  servlet:
    session:
      timeout: 30m
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org:
      springframework:
        jdbc:
          datasource: DEBUG
        web: DEBUG
      hibernate:
        type:
          descriptor:
            type: TRACE  # Logs the SQL bind parameters
            SQL: DEBUG   # Logs the SQL statements
app:
  # DB Properties
  url: jdbc:postgresql://localhost:5432/fc
  username: fc
  password: changeit